name: 'Simple custom container action'
description: 'Almost nothing'
inputs:
  name:
    description: 'Name to print'
    required: true
    default: 'Felipe'
outputs:
  msg:
    description: 'Message greeting the person pass in the input'
runs:
  using: 'docker'
  image: 'Dockerfile'
  ## NOTE: Remember to give proper permissions to all scripts used in the action (git update-index --chmod=+x *.sh) 
  ## If entrypoint is not set the default will be the one specified in Dockerfile ENTRYPOINT instruction
  #pre-entrypoint: 'setup.sh' # it does not work
  args:
    - ${{ inputs.name }}
    - 'polite'
